### PR TITLE
Add path finder for BancorPrice integration

### PR DESCRIPTION
**Pull request by uivlis**
Hey @mikedeshazer, it's been a long time since you put [that](https://gitcoin.co/issue/ProofSuite/OrFeedSmartContracts/4/3745) bounty, but I see now that you still haven't accepted my submitted work. Nevertheless, in this pull request I updated my work with the latest `BancorNetwork` address and functionality, but now I know why it didn't work. Because the rest of your code is, well... messy, to say the least. Not to mention that even the project truffle structure doesn't work when I try to compile (not that the compilation wouldn't succeed). It's obvious that one cannot make this work, and it's even more obvious you shouldn't spend ether trying to deploy those contracts until you have at least a compilation environment, some automated tests on your local network and manual testing on a test network. Only then I suggest you deploy to mainnet. Now, I can help you with all these, but please consider either accepting my bounty submission, either rejecting it altogether or cancelling the bounty (so that I free up a bounty slot on my dashboard). After that, we can discuss, if you wish, some form of collaboration that would be beneficial for both of us.

### CODE REVIEW

**Comment by mikedeshazer** [comment]
@uivlis thank for sharing your feedback. Yes, the truffle aspect was a submission that was included, but probably shouldn't have been. 
Regarding bancor, I deployed and tested previous submissions (and shared the contract addresses on the other repo in the issues) but couldn't couldn't get appropriate output. Will check this latest version!

**Comment by mikedeshazer** [comment]
@uivlis so far in trying to test your code, I get compilation errors
Specifically , line 76: function getExchangeRate ( string calldata fromSymbol, string calldata toSymbol, string calldata venue, uint256 amount ) external view returns ( uint256 );
In remix.

**Comment by mikedeshazer** [comment]
@uivlis also in bancor function 323 stack is too deep error. These error are when I compile with pragma solidity >=0.4.26 as specified in the pragma. Did you test with a different compiler version?

**Comment by mikedeshazer** [comment]
Also, reason it's on mainnet environment is that many of the the price data feeds (Kyber, Uniswap, Synthetix etc) dont work properly on the same testnests and it relies on these to function. That and that it is mostly consumed as readonly. What might make things easier is to just write a separate contract that works with bancor and then that contract could be called from the main contract as a proxy. Further, I can send small amount of ETH for deployment/testing on mainnet to save on gas.  I'm on telegram as @mikeproof

**Comment by uivlis** [comment]
Right, but Bancor is open source, so you can deploy a local instance of Bancor to testnet for test purposses, and then use the real world address. Regardless of testing, compilation inside the project should still work. I suggest you can use a starter kit, like this one: https://github.com/HQ20/starter-kit. It has everything you need for a blockchain workspace, and also for web-ui etc. Until then, I give up...
Regarding the function that doesn't compile, since the truffle compilation errors inside the project were related to the configuration file, I thought my code would pass...
